"""Alter Invoice_item with constraints ondelete

Revision ID: 40bd076a82e9
Revises: acadca126ed6
Create Date: 2024-09-04 16:10:47.481599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40bd076a82e9'
down_revision: Union[str, None] = 'acadca126ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoice_item_invoice_id_fkey', 'invoice_item', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_item', 'invoice', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_item', type_='foreignkey')
    op.create_foreign_key('invoice_item_invoice_id_fkey', 'invoice_item', 'invoice', ['invoice_id'], ['id'])
    # ### end Alembic commands ###
