"""Alter invoice_item with course name

Revision ID: acadca126ed6
Revises: 22bcb8ea4ada
Create Date: 2024-08-30 09:11:12.403286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acadca126ed6'
down_revision: Union[str, None] = '22bcb8ea4ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_item', sa.Column('course_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_item', 'course_name')
    # ### end Alembic commands ###
