"""Add admin table and alter invoice

Revision ID: f38487dd3d31
Revises: 16a2e8c16eee
Create Date: 2024-08-26 16:44:34.117720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38487dd3d31'
down_revision: Union[str, None] = '16a2e8c16eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('client_email', sa.String(), nullable=True))
    op.alter_column('invoice_item', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice_item', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('invoice', 'client_email')
    # ### end Alembic commands ###
